### ISSUE TITLE
can't bint to options

### ISSUE THREAD

**Issue by andikas** [psykolm22/ng2-google-place-autocomplete#11]
Hi,
need Help. I got an issue when I use this code.
I've follow the instalation steps, but still got this error.
Igot this error.
Unhandled Promise rejection: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'input'. (" class="input-group">
<input type="text" size="100" [(ngModel)] = "address" 
 [ERROR ->][options]='options' 
 (setAddress) = "getAddress($event)"
 (street_number) = 'street_number=$event'"): HomeComponent@40:1 ; Zone: <root> ; Task: Promise.then ; Value: 

Any suggestion?
Here's my module
`import {GooglePlaceModule} from 'ng2-google-place-autocomplete';

export const appRoutes: Routes = [
  { path: '', component: AppComponent, children:[
  		{ path: '', component: NavbarComponent, outlet: 'navbar'},
      	{ path: '', component: FooterComponent, outlet: 'footer'},
      	{ path: '', component: CopyrightComponent, outlet: 'copyright'},
      	{ path: '', component: HomeComponent},
      	{ path : 'property', component: PropertyComponent}
  ] }
];
@NgModule({
  	imports: [ 
  		BrowserModule, 
  		CarouselModule,
  		CommonModule,
    	FormsModule,
    	HttpModule,
    	GooglePlaceModule, 
  		DropdownModule.forRoot(), `

My Component
`export class AppComponent { 
	public options = {types: ['address'],componentRestrictions: { country: 'FR' }}
    getAddress(place:Object) {       
           console.log("Address", place);
       }
}`

and my input form same as with the tutorial.

**Comment by larschla** [comment]
Any news on this. I'm also getting this error.

**Comment by psykolm22** [comment]
This issue was moved to psykolm22/angular-google-place#7
