### ISSUE TITLE
Compiling project with ngc (for AOT) results in an error

### ISSUE THREAD

**Issue by jasonburrows** [psykolm22/ng2-google-place-autocomplete#12]
Looks like this module is not yet compatible with Angular 2 AOT.  Any chance to get it fixed?  

`Error: ENOENT: no such file or directory, open '/Development/front/build/node_modules/ng2-google-place-autocomplete/src/app/ng2-google-place.classes.metadata.json'`

Thanks!

**Comment by psykolm22** [comment]
This issue was moved to psykolm22/angular-google-place#8
