### ISSUE TITLE
Add location biaising

### ISSUE THREAD

**Issue by danyyacoub** [psykolm22/ng2-google-place-autocomplete#17]
Hi, is there a way to add location biasing in this plugin ? 
The idea is to add to options the bounds objects that contain south west coordinates and north east coordinates, it already exists in google maps api.

https://developers.google.com/maps/documentation/javascript/reference#AutocompleteService

Thanks,

**Comment by dionsteel** [comment]
this might have already been taken care of, but it seems like you could put this in the options object same as you would for types, etc like 
```
{
    "types": [ "(regions)" ],
    "componentRestrictions": { "country": "au" },
    "bounds": { 
        "east": east longitude,
        "north": north latitude,
        "south": south latitude,
        "west": west latitude
    }
}
```
could be wrong, haven't tested it, but pretty sure.

**Comment by psykolm22** [comment]
This issue was moved to psykolm22/angular-google-place#9
