### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by pavelbaykov89** [psykolm22/ng2-google-place-autocomplete#27]
I've added library to my web app but getting error:
Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Module parse failed: C:\Users\myuser\Documents\Projects\myproject\node_modules\ng2-google-place-autocomplete\src\app\ng2-google-place.module.ts Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
| import {GooglePlaceService} from './ng2-google-place.service'
| 
| @NgModule({
| imports: [CommonModule],
| providers: [GooglePlaceService],

I'm using Angular Universal and Prerendering

**Comment by psykolm22** [comment]
This issue was moved to psykolm22/angular-google-place#17
