### ISSUE TITLE
Is it compatible with angular4?

### ISSUE THREAD

**Issue by 02harleen** [psykolm22/ng2-google-place-autocomplete#28]
Hi, Is it compatible with angular4? I have used this package but this does not work. My versions are:-
angular:- 4.3.6
angular cli:- 1.2.6
zone.js:- 0.8.16

**Comment by francojay** [comment]
Yeah, it should work. 

This is how I implement it with material's input

```
              <md-input-container class="form-input-lg">
                <input ng2-google-place-autocomplete mdInput #billing_address1 [(ngModel)]="customer.billing_address1" formControlName="billing_address1" type="text" 
                placeholder="Billing Address 1" (setAddress)="getBillingAddress($event)">
              </md-input-container>
```

You really only need `ng2-google-place-autocomplete` and should have `(setAddress)`

**Comment by psykolm22** [comment]
This issue was moved to psykolm22/angular-google-place#18
