### ISSUE TITLE
Not able to set componentRestrictions : country dynamically

### ISSUE THREAD

**Issue by elan1984** [psykolm22/ng2-google-place-autocomplete#31]
We are trying to flip country code based on the radio selection and we are passing CountryCode ISO 3166-1 Alpha-2 for country code. 

Also i verified your as well demo, Flip of country also not working

**Comment by Mage111** [comment]
It's really a bug!
dose there is any way to change the country after initializing the control?

**Comment by psykolm22** [comment]
This issue was moved to psykolm22/angular-google-place#24
