### ISSUE TITLE
Not working with the new angular compilter

### ISSUE THREAD

**Issue by mhmo91** [psykolm22/ng2-google-place-autocomplete#4]
I'm on
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
Using angular-cli with webpack version     "angular-cli": "^1.0.0-beta.24",

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/index.d.ts, resolving symbol GooglePlaceModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/src/app/shared/ng2-google-place.module.ts, resolving symbol GooglePlaceModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/src/app/shared/ng2-google-place.module.ts

**Comment by mhmo91** [comment]
more about the issue
Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/index.d.ts, resolving symbol GooglePlaceModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/src/app/shared/ng2-google-place.module.ts, resolving symbol GooglePlaceModule in C:/Users/engmh/Desktop/eyekatcher/node_modules/ng2-google-place-autocomplete/src/app/shared/ng2-google-place.module.ts

**Comment by psykolm22** [comment]
Due to angular core change, Should be fix now with [Release 1.4.1](https://github.com/psykolm22/ng2-google-place-autocomplete/releases/tag/1.4.1)
