### ISSUE TITLE
Calling function 'makeDecorator'

### ISSUE THREAD

**Issue by pdkproitf** [psykolm22/ng2-google-place-autocomplete#5]
![screenshot from 2017-01-09 13-57-34](https://cloud.githubusercontent.com/assets/12691828/21759089/1e983b4e-d674-11e6-9bb4-c6df912fb6b7.jpg)

**Comment by psykolm22** [comment]
Due to angular core change, Should be fix now with [Release 1.4.1](https://github.com/psykolm22/ng2-google-place-autocomplete/releases/tag/1.4.1)
