### ISSUE TITLE
/node_modules/ng2-google-place-autocomplete/src/app/ng2-google-place.classes.ts:29:8  Parameter 'viewport' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by mamdi52** [psykolm22/ng2-google-place-autocomplete#6]
Can anyone have idea to resolve it?

**Comment by psykolm22** [comment]
You can solve it by set noImplicitAny to false (default value ) in your tsconfig.json, it will be solve for next release see :[commit:9f16ad05e71ce833ba523215c3534997ca179faa]( https://github.com/psykolm22/ng2-google-place-autocomplete/commit/9f16ad05e71ce833ba523215c3534997ca179faa )
