### ISSUE TITLE
Error with last version 

### ISSUE THREAD

**Issue by mmaryo** [psykolm22/ng2-google-place-autocomplete#8]
Hello, 

With last version of angular 2.4.5 and last version of ng2-google-place-autocomplete 1.4.1
I have this error 

    ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /home/mario/dev/project2/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /home/mario/dev/project2/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /home/mario/dev/project2/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /home/mario/dev/project2/node_modules/ng2-google-place-autocomplete/node_modules/@angular/core/index.d.ts, resolving symbol GooglePlaceModule in /home/mario/dev/project2/node_modules/ng2-google-place-autocomplete/src/app/ng2-google-place.module.ts, resolving symbol GooglePlaceModule in /home/mario/dev/project2/node_modules/ng2-google-place-autocomplete/src/app/ng2-google-place.module.ts

**Comment by psykolm22** [comment]
rebuild with @angular-cli 1.0.0-beta.30 and @angular 2.4.6[Release 1.4.2](https://github.com/psykolm22/ng2-google-place-autocomplete/releases/tag/1.4.2)

**Comment by mmaryo** [comment]
It's good 
thanks !
